# Generated by Django 4.0.3 on 2022-08-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapppassword',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
