# Generated by Django 4.0.3 on 2022-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_webapppassword_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPassword',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
                ('card_type', models.CharField(max_length=30)),
                ('card_number', models.IntegerField(max_length=12)),
                ('card_cvv', models.IntegerField(max_length=3)),
                ('card_atm_pin', models.IntegerField(max_length=4)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
