# Generated by Django 4.0.3 on 2022-08-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cardpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpassword',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='cardpassword',
            name='card_type',
        ),
        migrations.AddField(
            model_name='cardpassword',
            name='card_exp',
            field=models.CharField(default=1212, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardpassword',
            name='card_holder_name',
            field=models.CharField(default=12121, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardpassword',
            name='card_atm_pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardpassword',
            name='card_cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardpassword',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
