# Generated by Django 4.0.3 on 2022-09-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_cardpassword_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpassword',
            name='card_atm_pin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cardpassword',
            name='card_cvv',
            field=models.CharField(max_length=20),
        ),
    ]
