# Generated by Django 4.0.3 on 2022-09-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_cardpassword_card_atm_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpassword',
            name='card_atm_pin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cardpassword',
            name='card_cvv',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='webapppassword',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
